name: RSS to SafeW
on:
  schedule:
    - cron: "0 */3 16-22 * *"  # UTC16/19/22点 → 北京时间00/03/06点
    - cron: "*/15 23 * * *"   # UTC23点 → 北京时间07点（每15分钟触发）
    - cron: "*/15 0-1 * * *"  # UTC00-01点 → 北京时间08-09点（每15分钟触发）
    - cron: "*/7 2-15 * * *"  # UTC02-15点 → 北京时间10-23点（每7分钟触发）
  workflow_dispatch:  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RSS_GITHUB_PAT }}
          fetch-depth: 0

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip  
          cache-dependency-path: requirements.txt  

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  

      - name: 运行脚本
        env:
          SAFEW_BOT_TOKEN: ${{ secrets.SAFEW_BOT_TOKEN }}
          SAFEW_CHAT_ID: ${{ secrets.SAFEW_CHAT_ID }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        run: python rss_safew.py

      - name: 提交推送与待审核记录
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新推送和待审核记录"
          file_pattern: "sent_posts.json pending_tids.json"
          branch: main
